app:
  title: Scaffolded Backstage App
  baseUrl: http://10.143.2.4:3000

organization:
  name: My Company

backend:
  baseUrl: http://10.143.2.4:7007
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin:
      - http://localhost:3000
      - http://10.143.2.4:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

vast:
  host: 10.143.11.204
  username: ${VAST_USERNAME}
  password: ${VAST_PASSWORD}

proxy:
  '/vast-api':
    target: https://10.143.11.204/api
    allowedHeaders: ['Authorization']
    changeOrigin: true
    secure: false
    pathRewrite:
      '^/api/proxy/vast-api/?': '/api/'

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  # This section is now at the root level, which is correct.
  publicRoutes:
    - /api/proxy/vast-api
  providers:
    guest: {}

scaffolder: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

permission:
  enabled: true
  policy:
    '@backstage/plugin-permission-backend':
      policies:
        - policy: allow-all