app:
  title: Scaffolded Backstage App
  # Update the baseUrl to your machine's IP address
  baseUrl: http://10.143.2.4:3000

organization:
  name: My Company

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  # Update the baseUrl to your machine's IP address
  baseUrl: http://10.143.2.4:7007
  listen:
    port: 7007
    # Uncomment the host directive and set it to '0.0.0.0' to allow external connections
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin:
      - http://localhost:3000
      - http://10.143.2.4:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
    headers:
      - Content-Type
      - Authorization
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy: {}

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

scaffolder: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  authorization:
    allow:
      - permission: catalog.entity.read
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

#kubernetes: {}

permission:
  enabled: true
  policy:
    '@backstage/plugin-permission-backend':
      policies:
        - policy: allow-all
